export const regexValidation = [
    { title: 'email', regex: /^(?!.*@.*@)[a-zA-Z0-9.@+]+$/ },
    { title: 'password', regex: /^[\x20-\x7E]*$/ },
    { title: 'alphanumeric', regex: /^[a-zA-Z0-9]*$/ },
    { title: 'alphanumericwithspace', regex: /^[a-zA-Z0-9 ]*$/ },
    { title: 'mobile', regex: /^[0-9]*$/ },
    { title: 'alpha', regex: /^[A-Za-z ]*$/ },
    { title: 'upperCase', regex: /^[A-Z]*$/ },
    { title: 'upperCaseWithUnderScore', regex: /^[A-Z_]*$/ },
    { title: 'upperCaseWithUnderScoreAndNumber', regex: /^[A-Z_]*$/ },
    { title: 'gmaecode', regex: /^[A-Z0-9-]*$/ },
    { title: 'numberwithdot', regex: /^[0-9.]*$/ },
    { title: 'alphanumericwithdot', regex: /^[a-zA-Z0-9.]*$/ },
    { title: 'alphanumericwithunderscore', regex: /^[a-zA-Z0-9_]*$/ },
    { title: 'alphanumericwithquestionMark', regex: /^[a-zA-Z0-9? ]*$/ },
    { title: 'alphanumericwithampersand', regex: /^[a-zA-Z0-9& ]*$/ },
    { title: 'alphacolon', regex: /^[A-Za-z :]*$/ },
    // { title: 'userId', regex: /^[A-Za-z0-9_]*$/ },
    // { title: 'deviceId', regex: /^[A-Za-z0-9-]*$/ },
    // { title: 'ipv4', regex: /^[0-9.]*$/ },
    // { title: 'ipv6', regex: /^[0-9:]*$/ },
    // { title: 'website', regex: /^[a-zA-Z0-9.]+$/ },
    // { title: 'name', regex: /^^[a-zA-Z0-9]{1,20}$/ },
    // { title: 'alphanumericWithDot', regex: /^[a-zA-Z0-9.]*$/ },
    // { title: 'imageurl', regex: /^[A-Za-z/.]*$/ },
    // { title: 'all', regex: /^[\s\S]*$/ },
    // { title: 'numberWithDot', regex: /^[0-9.]*$/ },
  ];
  